# Uncomment the next line to define a global platform for your project
# platform :ios, ‘8.0’

target 'LocalNotification' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Toast-Swift', '~> 2.0.0'

  target 'LocalNotificationTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
